/** @Auth -- generated by lang_extract.py 
**  @Desc 这个文件是lang_extract.py自动生成，编辑自定义内容会被覆盖。
** @LastUpdatetime 2018-12-05 14:40:40 
**/
var _dict = (function(){
	return {
		"lang_name":"us-en",
		/** translate content start **/
		"疯一样的自由<br />":"crazy freedom<br />",
		/** new added **/
		"新增文字内容":"new text",
		/** end new added **/
		/** translate content end **/
	};
})();
