/**	@Auth -- generated by lang_extract.py 
**	@Desc 注意！！！在"auto content"区域内的内容将会被工具复写，不要在其中自定义内容！！！
**	可在"custom content"区域内编写自定义内容。 
** @LastUpdatetime 2018-12-05 20:50:24 
**/
var _dict = (function(){
	return {
		"lang_name":"zh-cn",
		// custom content start

		//本块内容不会被自动化工具编辑，可在本块内编辑自定义内容，也可以放开下面注释测试。
		//"自定义内容":"custom content",

		// end custom content


		// auto content start
		"疯一样的自由<br />":"",
		"新增文字重复内容":"",
		"新增文字内容2":"",
		// Added

		"新增文字内容3":"",

		// end Added


		// auto content end


	};
})();
